In [1]:

import numpy as np
import cv2
import glob


WAIT_TIME = 10
# termination criteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 140, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((7*9,3), np.float32)
objp[:,:2] = np.mgrid[0:9,0:7].T.reshape(-1,2)

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

images = glob.glob('*.png')

for fname in images:
    img = cv2.imread(fname)
    #img=cv2.flip(img,0)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

    # Find the chess board corners
    ret, corners = cv2.findChessboardCorners(gray, (9,7),None)

    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)

        corners2 = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
        imgpoints.append(corners2)

        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, (9,7), corners2,ret)
        cv2.imshow('img',img)
        cv2.waitKey(0)

cv2.destroyAllWindows()
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1],None,None)

# ---------- Saving the calibration -----------------
cv_file = cv2.FileStorage("fer_camara_3.yaml", cv2.FILE_STORAGE_WRITE)
cv_file.write("camera_matrix", mtx)
cv_file.write("dist_coeff", dist)
# note you *release* you don't close() a FileStorage object
cv_file.release()

print(mtx)
print(dist)


# File storage in OpenCV
cv_file = cv2.FileStorage("fer_camara_3.yaml", cv2.FILE_STORAGE_READ)

# Note : we also have to specify the type
# to retrieve otherwise we only get a 'None'
# FileNode object back instead of a matrix
camera_matrix = cv_file.getNode("camera_matrix").mat()
dist_matrix = cv_file.getNode("dist_coeff").mat()

print("camera_matrix : ", camera_matrix.tolist())
print("dist_matrix : ", dist_matrix.tolist())

cv_file.release()




[[345.04680835   0.         395.66904248]
 [  0.         363.37313381 252.02907193]
 [  0.           0.           1.        ]]
[[ 2.86702881e-02 -1.15442040e+00  6.22055321e-03 -4.58882081e-03
   5.47349913e+00]]
camera_matrix :  [[345.0468083466984, 0.0, 395.66904248218515], [0.0, 363.37313381326754, 252.029071926653], [0.0, 0.0, 1.0]]
dist_matrix :  [[0.02867028809256757, -1.1544204009685028, 0.0062205532059099716, -0.004588820805172539, 5.473499134658947]]


In [2]:
rvecs

[array([[ 0.04029444],
        [-0.04035828],
        [ 1.58266125]]),
 array([[ 0.04689956],
        [-0.02854415],
        [ 0.885272  ]]),
 array([[ 0.08530463],
        [-0.08552794],
        [ 2.53549406]]),
 array([[ 0.53439818],
        [-0.43568273],
        [ 1.49101949]]),
 array([[-0.40366529],
        [ 0.37452946],
        [ 1.64013347]]),
 array([[ 0.10302847],
        [-0.0061854 ],
        [ 1.61039137]]),
 array([[-0.04013506],
        [ 0.07133242],
        [-3.10138412]]),
 array([[ 0.51309734],
        [-0.44609755],
        [ 1.5226455 ]]),
 array([[ 0.1364264 ],
        [-0.07479315],
        [ 2.12469373]]),
 array([[-0.29549662],
        [ 0.61008586],
        [ 1.57497635]])]